apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    mixCoord:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 8Gi
      nodeSelector:
        milvus/role: misc
    streamingNode:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 80Gi
      nodeSelector:
        milvus/role: misc
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 8Gi
      nodeSelector:
        milvus/role: misc
      serviceType: NodePort
    queryNode:
      replicas: 1
      resources:
        limits:
          cpu: 32
          memory: 120Gi
      volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
        - name: tmp
          hostPath:
            path: /tmp
            type: ""
      nodeSelector:
        milvus/role: querynode
    dataNode:
      replicas: 1
      resources:
        limits:
          cpu: 16
          memory: 8Gi
      nodeSelector:
        milvus/role: misc
  config:
    common:
      DiskIndex:
        MaxDegree: 56
        SearchListSize: 100
        PQCodeBudgetGBRatio: 0.125
        SearchCacheBudgetGBRatio: 0.10
        BeamWidthRatio: 4
    queryNode:
      enableDisk: true
      segcore:
        tieredStorage:
          enabled: true
          warmup:
            scalarField: disable
            scalarIndex: disable
            vectorField: disable
            vectorIndex: disable
          evictionEnabled: true
          backgroundEvictionEnabled: true
          memoryLowWatermarkRatio: 0.75
          memoryHighWatermarkRatio: 0.80
          diskLowWatermarkRatio: 0.60
          diskHighWatermarkRatio: 0.70
          cacheTtl: 0
      mmap:
        vectorField: true
        vectorIndex: true
        scalarField: false
        scalarIndex: false
        jsonShredding: false
        growingMmapEnabled: false
        fixedFileSizeForMmapAlloc: 1
        maxDiskUsagePercentageForMmapAlloc: 50
      lazyload:
        enabled: true
        waitTimeout: 3600000
        requestResourceTimeout: 120000
        requestResourceRetryInterval: 2000
        maxRetryTimes: 10
        maxEvictPerRetry: 1
    localStorage:
      path: /tmp/milvus/cache/
  dependencies:
    msgStreamType: woodpecker
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
          - name: ETCD_QUOTA_BACKEND_BYTES
            value: "4294967296"
          - name: ETCD_HEARTBEAT_INTERVAL
            value: "500"
          - name: ETCD_ELECTION_TIMEOUT
            value: "25000"
          - name: ETCD_SNAPSHOT_COUNT
            value: "10000"
          - name: ETCD_ENABLE_PPROF
            value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 20Gi
            storageClass:
          replicaCount: 1
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi
          nodeSelector:
            milvus/role: minio
    storage:
      inCluster:
        values:
          mode: standalone
          resources:
            limits:
              cpu: 10
          persistence:
            storageClass:
            accessMode: ReadWriteOnce
            size: 144Gi
          nodeSelector:
            milvus/role: minio
